name: Publish

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: [test, build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
